version: '2'
services:
  cache:
    restart: always
    build:
      context: .
      dockerfile: extra/cache/Dockerfile
      args:
        MODE: prod
    expose:
      - "11211"

  hhvm:
    restart: always
    build:
      context: .
      dockerfile: extra/hhvm/Dockerfile
      args:
        MODE: prod
    depends_on:
      - cache
    expose:
      - "9000"

  nginx:
    restart: always
    build:
      context: .
      dockerfile: extra/nginx/Dockerfile
      args:
        TYPE: own
        MODE: prod
    depends_on:
      - hhvm
    ports:
      - "80:80"
      - "443:443"
